# Tool Registry - Central version control and metadata
# This is the single source of truth for all tool versions

tools:
  # Core development tools
  helix:
    description: "Modal text editor"
    type: github
    repo: helix-editor/helix
    version: "25.07.1"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  ripgrep:
    description: "Fast code search"
    type: github
    repo: BurntSushi/ripgrep
    version: "15.1.0"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  eza:
    description: "Modern ls replacement"
    type: github
    repo: eza-community/eza
    version: "v0.23.4"
    pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
  dust:
    description: "Disk usage analyzer"
    type: github
    repo: bootandy/dust
    version: "v1.2.3"
    pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
  zellij:
    description: "Terminal multiplexer"
    type: github
    repo: zellij-org/zellij
    version: "v0.43.1"
    pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
  taplo:
    description: "TOML toolkit"
    type: github
    repo: tamasfe/taplo
    version: "0.10.0"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  rclone:
    description: "rsync for cloud storage"
    type: github
    repo: rclone/rclone
    version: "v1.71.2"
    pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
  # Python tools
  ruff:
    description: "Python linter and formatter"
    type: github
    repo: astral-sh/ruff
    version: "0.14.5"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  uv:
    description: "Python package manager"
    type: github
    repo: astral-sh/uv
    version: "0.9.9"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  # Language servers
  pyright:
    description: "Python language server"
    type: npm
    package: pyright
    version: "1.1.407"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  prettier:
    description: "Code formatter"
    type: npm
    package: prettier
    version: "3.6.2"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  yaml_language_server:
    description: "YAML language server"
    type: npm
    package: yaml-language-server
    version: "1.19.2"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
