name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        id: notes
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges | head -20)
          else
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges ${PREV_TAG}..HEAD)
          fi
          
          cat > notes.md << EOF
          $(echo "$COMMITS" | grep "feat:" | sed 's/feat: //' || true)
          $(echo "$COMMITS" | grep "fix:" | sed 's/fix: //' || true)
          $(echo "$COMMITS" | grep -v -E "^- (feat|fix|docs|chore):" || true)
          
          ### Install
          \`\`\`bash
          sh -c "\$(curl -fsLS get.chezmoi.io)" -- -b \$HOME/.local/bin init --apply 0xAndrii
          \`\`\`
          EOF

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: notes.md